import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import { Providers } from "./providers"

const poppin = Poppins({ subsets: ["latin"], weight: ["400"] })

export const metadata: Metadata = {
  title: "React Fetching data API",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppin.className}  bg-slate-800 text-white`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
